version: "3.3"
services:

  consul:
    image: consul:1.6.2
    command: ["consul","agent","-config-file=/config/consul-single-dc.hcl","-config-dir=/config"]
    volumes:
      - "./consul_config:/config"
    ports:
      - 8500:8500
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  database:
    image: joatmon08/expense-db:mssql
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Testing!123
  database_proxy:
    image: joatmon08/consul-envoy:1.6.2-1.11.1
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/database.hcl
    volumes:
      - "./circuit_breaking/consul_config:/config"
    command: ["consul", "connect", "envoy", "-sidecar-for", "database"]
    network_mode: "service:database"

  expense:
    image: joatmon08/expense:dotnet
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    ports:
      - 5001:5001
  expense_proxy:
    image: joatmon08/consul-envoy:1.6.2-1.11.1
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/expense.hcl
    volumes:
      - "./circuit_breaking/consul_config:/config"
    command: ["consul", "connect", "envoy", "-sidecar-for", "expense", "--", "-l", "trace"]
    network_mode: "service:expense"

  # report:
  #   image: joatmon08/report:dotnet
  #   networks:
  #     vpcbr:
  #       ipv4_address: 10.5.0.5
  #   ports:
  #     - 5002:5002
  # report_proxy:
  #   image: joatmon08/consul-envoy:1.6.2-1.11.1
  #   environment:
  #     CONSUL_HTTP_ADDR: 10.5.0.2:8500
  #     CONSUL_GRPC_ADDR: 10.5.0.2:8502
  #     SERVICE_CONFIG: /config/report.hcl
  #   volumes:
  #     - "./circuit_breaking/consul_config:/config"
  #   command: ["consul", "connect", "envoy", "-sidecar-for", "report", "--", "-l", "debug"]
  #   network_mode: "service:report"

  jaeger:
    image: jaegertracing/all-in-one:1.13
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.10

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
