version: "3.3"
services:

  expense-v2:
    image: joatmon08/expense:dotnet
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
  expense_proxy_v2:
    image: joatmon08/consul-envoy:1.6.2-1.11.1
    restart: always
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/expense_v2.hcl
      CENTRAL_CONFIG_DIR: /central_config
    volumes:
      - "./service_config:/config"
      - "./traffic_config:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "expense-v2", "--", "-l", "error"]
    network_mode: "service:expense-v2"
  
networks:
  vpcbr:
    external:
      name: dotnet-service-mesh-example_vpcbr