version: "3.3"
services:

  consul:
    image: consul:1.6.1
    command: ["consul","agent","-config-file=/config/consul.hcl","-config-dir=/config"]
    volumes:
      - "./circuit_breaking/consul_config:/config"
    ports:
      - 8500:8500
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  expense-db:
    image: joatmon08/expense-db:mssql
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Testing!123
  expensedb_envoy:
    image: envoyproxy/envoy-alpine:v1.9.1
    command: ["envoy","-c","/config/expense_db_envoy.json"]
    volumes:
      - "./circuit_breaking/envoy_config:/config"
    network_mode: "service:expense-db"

  expense:
    image: joatmon08/expense:dotnet
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    ports:
      - 5001:5001
  expense_proxy:
    image: envoyproxy/envoy-alpine:v1.9.1
    command: ["envoy","-c","/config/upstream_envoy.json"]
    volumes:
      - "./circuit_breaking/envoy_config:/config"
    network_mode: "service:expense"

  report:
    image: joatmon08/report:dotnet
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    ports:
      - 5002:5002
  report_proxy:
    image: envoyproxy/envoy-alpine:v1.9.1
    command: ["envoy","-c","/config/downstream_envoy.json"]
    volumes:
      - "./circuit_breaking/envoy_config:/config"
    network_mode: "service:report"

  jaeger:
    image: jaegertracing/all-in-one:1.13
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.10

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
